[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pencil_finance = "6yovnUkuEdNBGgxqDzUgQLkGg75h2zDQsNwG6Zipp5ML"

[programs.devnet]
pencil_finance = "6yovnUkuEdNBGgxqDzUgQLkGg75h2zDQsNwG6Zipp5ML"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
